---
title: "Speech Example"
format:
  revealjs:
    speech:
      nextKeyword: "nextslide"
      prevKeyword: "previousslide"
      lastKeyword: "lastslide"
      firstKeyword: "firstslide"
revealjs-plugins:
  - speech
---

# Intro

This Quarto extension allows you talk to your presentation and control it. Let's go over how Bob's day was. Bob is a random person. Make sure you have your microphone enabled for the web page. Read the slide for instructions.

::: footer
Say "next slide" to go to the next slide or "last slide" to skip to the last slide.
:::

## Getting up

- Turn off alarm
- Get out of bed
- Take a shower

::: footer
Say "next slide" to continue to the next slide or "previous slide" to go to the previous slide.
:::

## Breakfast

- Eat eggs
- Drink coffee

::: footer
Say "next slide" to continue to the next slide.
:::

## Dinner

- Eat spaghetti
- Drink wine

::: footer
Say "next slide" to continue to the next slide.
:::

## Going to sleep

<section>
- Get in bed
- Count sheep (say "1 Sheep" then "2 Sheep" then "3 Sheep" to count sheep.)
  <ol>
    <li class="fragment" data-speech="onesheep">Sheep 1</li>
    <li class="fragment" data-speech="twosheep">Sheep 2</li>
    <li class="fragment" data-speech="threesheep">Sheep 3

    ... Zzzzzzz (say "next slide")
    </li>
  </ol>
</section>

# Zzzzzzz

Say "moving along" to go to the next slide.

<section data-speech-next="movingalong">
</section>

# Conclusion

Hope that was fun. You just used your browser's speech recognition API to control these RevealJS slides. You can change the keyword phrases to whatever you want in the YAML header. The defaults are listed in the [repo readme](https://github.com/parmsam/quarto-flashcards/blob/main/README.md#using). There's also some room for customization covered in the README.

Oh, almost forgot. You can go a specific slide by saying "go to slide number 3" or "go to slide number 4" etc.

::: footer 
Say "first slide" to go to the first slide. 
:::